name: ams
description: Developed by Bistech Ghana.

publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.0.0
  data_table_2: ^2.3.7
  date_format: ^2.0.6
  dropdown_search: ^5.0.2
  encrypt: ^5.0.1
  fluent_ui: ^4.4.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.2
  flutter_animate: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  multi_dropdown: ^1.0.9
  multiple_search_selection: ^2.4.1
  multiselect: ^0.0.7
  multiselect_formfield: ^0.1.7
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  pdf: ^3.8.3
  printing: ^5.9.3
  provider: ^6.0.3
  select_searchable_list: ^0.1.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^20.2.49
  system_theme: ^2.1.0
  time: ^2.1.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  fluandroid: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
