name: ams
description: Our biometric attendance system integrates with your existing
  devices to directly pull data and generate accurate reports on absentees,
  monthly attendance, overtime, and more. You can also receive SMS alerts for
  real-time updates on attendance status. With our system, managing attendance
  has never been easier or more efficient. Developed by Bistech Ghana. website:\
  https://bistechgh.com/

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.1.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.0.1
  data_table_2: ^2.5.3
  date_format: ^2.0.7
  dropdown_search: ^5.0.6
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.0.0
  intl: ^0.18.1
  multiple_search_selection: ^2.5.3
  multiselect_formfield: ^0.1.7
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.0.5
  select_searchable_list: ^0.1.5
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^22.1.34
  time: ^2.1.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  fluandroid: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/finger.png"
  web:
    generate: true
    image_path: "assets/icons/finger.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/finger.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/finger.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
